import type { UiLabels } from "./locale";
import { formatMmSs } from "./helpers";

// ─── Data model ───────────────────────────────────────────────────────────────

export interface ExportRow {
  label: string;
  /** Allotted duration in seconds */
  durationSec: number;
  /** Elapsed ms (0 when idle) */
  elapsedMs: number;
  status: "idle" | "running" | "paused";
}

export interface ExportSection {
  key: string;
  label: string;
  rows: ExportRow[];
}

export interface ExportData {
  weekLabel: string;
  meetingStartTime: string;
  sections: ExportSection[];
}

// ─── Plain-text builder ───────────────────────────────────────────────────────

const SECTION_EMOJI: Record<string, string> = {
  opening:   "🎵",
  treasures: "📖",
  ministry:  "📣",
  living:    "🏠",
  closing:   "🙏",
};

function statusSymbol(row: ExportRow): string {
  if (row.status === "idle") return "—";
  const over = row.elapsedMs > row.durationSec * 1000;
  return over ? "⚠" : "✓";
}

export function buildExportText(data: ExportData): string {
  const lines: string[] = [];

  lines.push(`⏱ JW Meeting Timer`);
  lines.push(data.weekLabel);
  lines.push(`🕐 ${data.meetingStartTime}`);

  for (const section of data.sections) {
    if (!section.rows.length) continue;
    const emoji = SECTION_EMOJI[section.key] ?? "📋";
    lines.push("");
    lines.push(`${emoji} ${section.label.toUpperCase()}`);

    for (const row of section.rows) {
      const allotted = `${Math.round(row.durationSec / 60)} min`;
      if (row.status === "idle") {
        lines.push(`  • ${row.label} (${allotted})`);
      } else {
        const elapsed = formatMmSs(row.elapsedMs);
        const sym = statusSymbol(row);
        lines.push(`  • ${row.label} (${allotted}) → ${elapsed} ${sym}`);
      }
    }
  }

  return lines.join("\n");
}

// ─── Print/PDF HTML builder ───────────────────────────────────────────────────

const SECTION_COLOR: Record<string, string> = {
  opening:   "#6b7280",
  treasures: "#0d9488",
  ministry:  "#d97706",
  living:    "#e11d48",
  closing:   "#6b7280",
};

export function buildPrintHtml(data: ExportData, labels: UiLabels): string {
  const rows: string[] = [];

  for (const section of data.sections) {
    if (!section.rows.length) continue;
    const color = SECTION_COLOR[section.key] ?? "#6b7280";
    const emoji = SECTION_EMOJI[section.key] ?? "📋";

    rows.push(`
      <tr class="section-header">
        <td colspan="3" style="background:${color};color:#fff;padding:6px 10px;font-weight:700;font-size:0.85rem;">
          ${emoji} ${section.label}
        </td>
      </tr>`);

    for (const row of section.rows) {
      const allotted = `${Math.round(row.durationSec / 60)} min`;
      const elapsed = row.status !== "idle" ? formatMmSs(row.elapsedMs) : "—";
      const over = row.status !== "idle" && row.elapsedMs > row.durationSec * 1000;
      const elapsedStyle = over ? "color:#dc2626;font-weight:700;" : "";
      const sym = row.status === "idle" ? "" : (over ? " ⚠" : " ✓");

      rows.push(`
        <tr>
          <td style="padding:5px 10px;">${row.label}</td>
          <td style="padding:5px 10px;text-align:center;color:#6b7280;">${allotted}</td>
          <td style="padding:5px 10px;text-align:right;${elapsedStyle}">${elapsed}${sym}</td>
        </tr>`);
    }
  }

  // Use labels.shareBtn locale as a rough "this doc was generated by" note
  void labels;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>JW Meeting Timer — ${escapeHtml(data.weekLabel)}</title>
  <style>
    body { font-family: system-ui, sans-serif; font-size: 14px; color: #111; margin: 0; padding: 1.5rem; }
    h1 { font-size: 1.1rem; margin: 0 0 0.25rem; }
    .meta { color: #6b7280; font-size: 0.85rem; margin-bottom: 1rem; }
    table { width: 100%; border-collapse: collapse; }
    tr:nth-child(even) { background: #f9fafb; }
    td { border-bottom: 1px solid #e5e7eb; vertical-align: middle; }
    .section-header td { border: none; }
    @media print { body { padding: 0; } }
  </style>
</head>
<body>
  <h1>⏱ JW Meeting Timer</h1>
  <p class="meta">${escapeHtml(data.weekLabel)} · 🕐 ${escapeHtml(data.meetingStartTime)}</p>
  <table>
    ${rows.join("")}
  </table>
  <script>window.onload = () => window.print();<\/script>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

// ─── Actions ──────────────────────────────────────────────────────────────────

/**
 * Share text via the Web Share API (mobile).
 * Falls back to clipboard on desktop. Shows a brief toast on success.
 */
export async function shareText(text: string, copyOk: string, toastEl: HTMLElement): Promise<void> {
  if (navigator.share) {
    try {
      await navigator.share({ text });
      return;
    } catch {
      // User cancelled or API failed — fall through to clipboard
    }
  }
  try {
    await navigator.clipboard.writeText(text);
    showToast(toastEl, copyOk);
  } catch {
    // Last resort: select a textarea
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.focus();
    ta.select();
    document.execCommand("copy");
    document.body.removeChild(ta);
    showToast(toastEl, copyOk);
  }
}

/** Open a new window with print-ready HTML and trigger the browser print dialog. */
export function printReport(html: string): void {
  const win = window.open("", "_blank", "width=800,height=600");
  if (!win) return;
  win.document.open();
  win.document.write(html);
  win.document.close();
}

function showToast(el: HTMLElement, message: string): void {
  el.setText(message);
  el.addClass("jw-timer-toast--visible");
  window.setTimeout(() => el.removeClass("jw-timer-toast--visible"), 2500);
}
